package com.olympus.model;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceIndex;
import com.gigaspaces.metadata.index.SpaceIndexType;

import java.math.BigDecimal;
/*
*
 * This class was auto-generated by GigaSpaces
*/


@SpaceClass
public class REAL_TIME_FUTURES {
    private String id;
    private long DATA_DATE;
    private long DATA_RECEIVED_TIMESTAMP;
    private String TICKER;
    private BigDecimal LAST_PRICE;
    private long  VOLUME_TDY;
    private BigDecimal _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private BigDecimal _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private BigDecimal _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private long LAST_PRICE_TIME_TODAY_REALTIME;
    private long TRADING_DT_REALTIME;
    private long PX_YEST_DT;
    private BigDecimal BID;
    private BigDecimal ASK;
    private BigDecimal VOLUME;
    private long LAST_TRADE_PRICE_TIME_TODAY_RT;
    private String CRNCY;

    public REAL_TIME_FUTURES() {
    }

    @SpaceId(autoGenerate = true)
    public String getId() {
        return TICKER + DATA_RECEIVED_TIMESTAMP + REAL_TIME_FUTURES.class.getName().hashCode();
    }

    public void setId(String id) {
        this.id = id;
    }


    public long getDATA_DATE() {
        return DATA_DATE;
    }

    public void setDATA_DATE(long DATA_DATE) {
        this.DATA_DATE = DATA_DATE;
    }

    @SpaceIndex(type = SpaceIndexType.ORDERED)
    public long getDATA_RECEIVED_TIMESTAMP() {
        return DATA_RECEIVED_TIMESTAMP;
    }

    public void setDATA_RECEIVED_TIMESTAMP(long DATA_RECEIVED_TIMESTAMP) {
        this.DATA_RECEIVED_TIMESTAMP = DATA_RECEIVED_TIMESTAMP;
    }

    @SpaceIndex(type = SpaceIndexType.EQUAL)
    public String getTICKER() {
        return TICKER;
    }

    public void setTICKER(String TICKER) {
        this.TICKER = TICKER;
    }

    public BigDecimal getLAST_PRICE() {
        return LAST_PRICE;
    }

    public void setLAST_PRICE(BigDecimal LAST_PRICE) {
        this.LAST_PRICE = LAST_PRICE;
    }

    public long getVOLUME_TDY() {
        return VOLUME_TDY;
    }

    public void setVOLUME_TDY(long VOLUME_TDY) {
        this.VOLUME_TDY = VOLUME_TDY;
    }

    public BigDecimal get_5_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public void set_5_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _5_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._5_DAY_AVERAGE_VOLUME_AT_TIME_RT = _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public BigDecimal get_20_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public void set_20_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _20_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._20_DAY_AVERAGE_VOLUME_AT_TIME_RT = _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public BigDecimal get_30_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public void set_30_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _30_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._30_DAY_AVERAGE_VOLUME_AT_TIME_RT = _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public long getLAST_PRICE_TIME_TODAY_REALTIME() {
        return LAST_PRICE_TIME_TODAY_REALTIME;
    }

    public void setLAST_PRICE_TIME_TODAY_REALTIME(long LAST_PRICE_TIME_TODAY_REALTIME) {
        this.LAST_PRICE_TIME_TODAY_REALTIME = LAST_PRICE_TIME_TODAY_REALTIME;
    }

    public long getTRADING_DT_REALTIME() {
        return TRADING_DT_REALTIME;
    }

    public void setTRADING_DT_REALTIME(long TRADING_DT_REALTIME) {
        this.TRADING_DT_REALTIME = TRADING_DT_REALTIME;
    }

    public long getPX_YEST_DT() {
        return PX_YEST_DT;
    }

    public void setPX_YEST_DT(long PX_YEST_DT) {
        this.PX_YEST_DT = PX_YEST_DT;
    }

    public BigDecimal getBID() {
        return BID;
    }

    public void setBID(BigDecimal BID) {
        this.BID = BID;
    }

    public BigDecimal getASK() {
        return ASK;
    }

    public void setASK(BigDecimal ASK) {
        this.ASK = ASK;
    }

    public BigDecimal getVOLUME() {
        return VOLUME;
    }

    public void setVOLUME(BigDecimal VOLUME) {
        this.VOLUME = VOLUME;
    }

    public long getLAST_TRADE_PRICE_TIME_TODAY_RT() {
        return LAST_TRADE_PRICE_TIME_TODAY_RT;
    }

    public void setLAST_TRADE_PRICE_TIME_TODAY_RT(long LAST_TRADE_PRICE_TIME_TODAY_RT) {
        this.LAST_TRADE_PRICE_TIME_TODAY_RT = LAST_TRADE_PRICE_TIME_TODAY_RT;
    }

    public String getCRNCY() {
        return CRNCY;
    }

    public void setCRNCY(String CRNCY) {
        this.CRNCY = CRNCY;
    }


}

