package bpipe_rt;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceIndex;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.gigaspaces.metadata.index.SpaceIndexType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
/*
*
 * This class was auto-generated by GigaSpaces
*/


@Entity
@Table(name = "REAL_TIME_FUTURES")
@SpaceClass
public class REAL_TIME_FUTURES implements PartitionedTable {
    private String id;
    private long DATA_DATE;
    private long DATA_RECEIVED_TIMESTAMP;
    private String TICKER;
    private BigDecimal LAST_PRICE;
    private BigDecimal SIZE_LAST_TRADE;
    private long DBTIMESTAMP;
    private String CRNCY;
    private BigDecimal VOLUME_TDY;
    private BigDecimal _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private BigDecimal _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private BigDecimal _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private long LAST_PRICE_TIME_TODAY_REALTIME;
    private long TRADING_DT_REALTIME;
    private long PX_YEST_DT;
    private long LAST_TRADE_PRICE_TIME_TODAY_RT;
    private BigDecimal BID;
    private BigDecimal ASK;
    private BigDecimal VOLUME;

    public REAL_TIME_FUTURES() {
    }

    @Id
    @SpaceId(autoGenerate = true)
    @SpaceIndex(unique = true)
    @Column(name = "Id")
    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "DATA_DATE")
    @Override
    public long getDATA_DATE() {
        return DATA_DATE;
    }

    @Override
    public void setDATA_DATE(long DATA_DATE) {
        this.DATA_DATE = DATA_DATE;
    }

    @SpaceIndex(type = SpaceIndexType.ORDERED)
    @Column(name = "DATA_RECEIVED_TIMESTAMP")
    @Override
    public long getDATA_RECEIVED_TIMESTAMP() {
        return DATA_RECEIVED_TIMESTAMP;
    }

    @Override
    public void setDATA_RECEIVED_TIMESTAMP(long DATA_RECEIVED_TIMESTAMP) {
        this.DATA_RECEIVED_TIMESTAMP = DATA_RECEIVED_TIMESTAMP;
    }

    @SpaceIndex(type = SpaceIndexType.EQUAL)
    @SpaceRouting
    @Column(name = "TICKER")
    @Override
    public String getTICKER() {
        return TICKER;
    }

    @Override
    public void setTICKER(String TICKER) {
        this.TICKER = TICKER;
    }

    @Column(name = "LAST_PRICE")
    @Override
    public BigDecimal getLAST_PRICE() {
        return LAST_PRICE;
    }

    @Override
    public void setLAST_PRICE(BigDecimal LAST_PRICE) {
        this.LAST_PRICE = LAST_PRICE;
    }

    @Column(name = "SIZE_LAST_TRADE")
    @Override
    public BigDecimal getSIZE_LAST_TRADE() {
        return SIZE_LAST_TRADE;
    }

    @Override
    public void setSIZE_LAST_TRADE(BigDecimal SIZE_LAST_TRADE) {
        this.SIZE_LAST_TRADE = SIZE_LAST_TRADE;
    }

    @Column(name = "DBTIMESTAMP")
    @Override
    public long getDBTIMESTAMP() {
        return DBTIMESTAMP;
    }
    @Override
    public void setDBTIMESTAMP(long DBTIMESTAMP) {
        this.DBTIMESTAMP = DBTIMESTAMP;
    }

    @Column(name = "CRNCY")
    @Override
    public String getCRNCY() {
        return CRNCY;
    }

    @Override
    public void setCRNCY(String CRNCY) {
        this.CRNCY = CRNCY;
    }

    @Column(name = "VOLUME_TDY")
    @Override
    public BigDecimal getVOLUME_TDY() {
        return VOLUME_TDY;
    }

    @Override
    public void setVOLUME_TDY(BigDecimal VOLUME_TDY) {
        this.VOLUME_TDY = VOLUME_TDY;
    }

    @Column(name = "5_DAY_AVERAGE_VOLUME_AT_TIME_RT")
    @Override
    public BigDecimal get_5_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    @Override
    public void set_5_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _5_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._5_DAY_AVERAGE_VOLUME_AT_TIME_RT = _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    @Column(name = "20_DAY_AVERAGE_VOLUME_AT_TIME_RT")
    @Override
    public BigDecimal get_20_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    @Override
    public void set_20_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _20_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._20_DAY_AVERAGE_VOLUME_AT_TIME_RT = _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    @Column(name = "30_DAY_AVERAGE_VOLUME_AT_TIME_RT")
    @Override
    public BigDecimal get_30_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    @Override
    public void set_30_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _30_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._30_DAY_AVERAGE_VOLUME_AT_TIME_RT = _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    @Column(name = "LAST_PRICE_TIME_TODAY_REALTIME")
    @Override
    public long getLAST_PRICE_TIME_TODAY_REALTIME() {
        return LAST_PRICE_TIME_TODAY_REALTIME;
    }

    @Override
    public void setLAST_PRICE_TIME_TODAY_REALTIME(long LAST_PRICE_TIME_TODAY_REALTIME) {
        this.LAST_PRICE_TIME_TODAY_REALTIME = LAST_PRICE_TIME_TODAY_REALTIME;
    }

    @Column(name = "TRADING_DT_REALTIME")
    @Override
    public long getTRADING_DT_REALTIME() {
        return TRADING_DT_REALTIME;
    }

    @Override
    public void setTRADING_DT_REALTIME(long TRADING_DT_REALTIME) {
        this.TRADING_DT_REALTIME = TRADING_DT_REALTIME;
    }

    @Column(name = "PX_YEST_DT")
    @Override
    public long getPX_YEST_DT() {
        return PX_YEST_DT;
    }

    @Override
    public void setPX_YEST_DT(long PX_YEST_DT) {
        this.PX_YEST_DT = PX_YEST_DT;
    }

    @Column(name = "LAST_TRADE_PRICE_TIME_TODAY_RT")
    public long getLAST_TRADE_PRICE_TIME_TODAY_RT() {
        return LAST_TRADE_PRICE_TIME_TODAY_RT;
    }

    public void setLAST_TRADE_PRICE_TIME_TODAY_RT(long LAST_TRADE_PRICE_TIME_TODAY_RT) {
        this.LAST_TRADE_PRICE_TIME_TODAY_RT = LAST_TRADE_PRICE_TIME_TODAY_RT;
    }

    @Column(name = "BID")
    public BigDecimal getBID() {
        return BID;
    }

    public void setBID(BigDecimal BID) {
        this.BID = BID;
    }

    @Column(name = "ASK")
    public BigDecimal getASK() {
        return ASK;
    }

    public void setASK(BigDecimal ASK) {
        this.ASK = ASK;
    }

    @Column(name = "VOLUME")
    public BigDecimal getVOLUME() {
        return VOLUME;
    }

    public void setVOLUME(BigDecimal VOLUME) {
        this.VOLUME = VOLUME;
    }
}

