package bpipe_rt;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceIndex;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.gigaspaces.metadata.index.SpaceIndexType;

import java.math.BigDecimal;

/*
 *
 * This class was auto-generated by GigaSpaces
 */


@SpaceClass
public class REAL_TIME implements PartitionedTable {
    private long DATA_DATE;
    private long DATA_RECEIVED_TIMESTAMP;
    private String TICKER;
    private BigDecimal LAST_PRICE;
    private long SIZE_LAST_TRADE;
    private long DB_TIMESTAMP;
    private BigDecimal PX_YEST_CLOSE;
    private String CRNCY;
    private BigDecimal VOLUME;
    private BigDecimal _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private BigDecimal _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private BigDecimal _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    private long TRADING_DT_REALTIME;
    private long PX_YEST_DT;

    public REAL_TIME() {
    }

    @SpaceId(autoGenerate = true)
    public String getId() {
        return TICKER + DATA_RECEIVED_TIMESTAMP + REAL_TIME.class.getName().hashCode();
    }

    public void setId(String id) {
    }


    public long getDATA_DATE() {
        return DATA_DATE;
    }

    public void setDATA_DATE(long DATA_DATE) {
        this.DATA_DATE = DATA_DATE;
    }

    @SpaceIndex(type = SpaceIndexType.ORDERED)
    public long getDATA_RECEIVED_TIMESTAMP() {
        return DATA_RECEIVED_TIMESTAMP;
    }

    public void setDATA_RECEIVED_TIMESTAMP(long DATA_RECEIVED_TIMESTAMP) {
        this.DATA_RECEIVED_TIMESTAMP = DATA_RECEIVED_TIMESTAMP;
    }

    @SpaceIndex(type = SpaceIndexType.EQUAL)
    @SpaceRouting
    public String getTICKER() {
        return TICKER;
    }

    public void setTICKER(String TICKER) {
        this.TICKER = TICKER;
    }

    public BigDecimal getLAST_PRICE() {
        return LAST_PRICE;
    }

    public void setLAST_PRICE(BigDecimal LAST_PRICE) {
        this.LAST_PRICE = LAST_PRICE;
    }

    public long getSIZE_LAST_TRADE() {
        return SIZE_LAST_TRADE;
    }

    public void setSIZE_LAST_TRADE(long SIZE_LAST_TRADE) {
        this.SIZE_LAST_TRADE = SIZE_LAST_TRADE;
    }

    public BigDecimal get_5_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public void set_5_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _5_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._5_DAY_AVERAGE_VOLUME_AT_TIME_RT = _5_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public BigDecimal get_20_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public void set_20_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _20_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._20_DAY_AVERAGE_VOLUME_AT_TIME_RT = _20_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public BigDecimal get_30_DAY_AVERAGE_VOLUME_AT_TIME_RT() {
        return _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public void set_30_DAY_AVERAGE_VOLUME_AT_TIME_RT(BigDecimal _30_DAY_AVERAGE_VOLUME_AT_TIME_RT) {
        this._30_DAY_AVERAGE_VOLUME_AT_TIME_RT = _30_DAY_AVERAGE_VOLUME_AT_TIME_RT;
    }

    public long getDB_TIMESTAMP() {
        return DB_TIMESTAMP;
    }

    public void setDB_TIMESTAMP(long DB_TIMESTAMP) {
        this.DB_TIMESTAMP = DB_TIMESTAMP;
    }

    public long getTRADING_DT_REALTIME() {
        return TRADING_DT_REALTIME;
    }

    public void setTRADING_DT_REALTIME(long TRADING_DT_REALTIME) {
        this.TRADING_DT_REALTIME = TRADING_DT_REALTIME;
    }

    public long getPX_YEST_DT() {
        return PX_YEST_DT;
    }

    public void setPX_YEST_DT(long PX_YEST_DT) {
        this.PX_YEST_DT = PX_YEST_DT;
    }

    public BigDecimal getPX_YEST_CLOSE() {
        return PX_YEST_CLOSE;
    }

    public void setPX_YEST_CLOSE(BigDecimal PX_YEST_CLOSE) {
        this.PX_YEST_CLOSE = PX_YEST_CLOSE;
    }

    public BigDecimal getVOLUME() {
        return VOLUME;
    }

    public void setVOLUME(BigDecimal VOLUME) {
        this.VOLUME= VOLUME;
    }

    public String getCRNCY() {
        return CRNCY;
    }

    public void setCRNCY(String CRNCY) {
        this.CRNCY = CRNCY;
    }


}

